---
- name: MongoDB | Debian | Install dependent package
  ansible.builtin.apt:
    name: gnupg

- name: MongoDB | Debian | Import apt key
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc

- name: MongoDB | Debian | Add apt repository
  ansible.builtin.apt_repository:
    repo: "{{ mongodb_repository }}"
    filename: mongodb-org-{{ mongodb_version }}
    update_cache: true

- name: MongoDB | Debian | Install mongodb client
  ansible.builtin.apt:
    name: mongodb-org-shell
  when: mongodb_install_client

- name: MongoDB | Debian | Install mongodb-org
  ansible.builtin.apt:
    name: mongodb-org
  when: mongodb_install_service
