---
namespace: ericsysmin
name: databases
version: 1.1.0
readme: README.md
authors:
  - Eric Anderson <eric.sysmin@gmail.com> (https://ericsysmin.com)
description: Collection of System Administration Roles
license_file: LICENSE
tags:
  - pgadmin4
  - postgres
  - databases
  - database
dependencies: {}
repository: https://github.com/ericsysmin/ansible-collection-databases
documentation: https://github.com/ericsysmin/ansible-collection-databases
homepage: https://github.com/ericsysmin/ansible-collection-databases
issues: https://github.com/ericsysmin/ansible-collection-databases/issues
