---
galaxy_info:
  author: aeric
  description: Ansible role to configure postgresql
  company: VMware
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - wily
        - xenial
  galaxy_tags: []
dependencies: []
