---
# code: language=ansible

- name: Converge
  hosts: all
  pre_tasks:
    - name: Update package cache
      ansible.builtin.package:
        update_cache: true
      changed_when: false
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2
  tasks:
    - name: Run the Ansible role
      ansible.builtin.include_role:
        name: ericsysmin.databases.pgadmin4
