name: "ericsysmin.databases.mongodb"
on:
  push:
    paths:
      - "roles/mongodb/**"
      - "molecule/mongodb/**"
      - ".github/workflows/mongodb.yml"
  pull_request:
    paths:
      - "roles/mongodb/**"
      - "molecule/mongodb/**"
      - ".github/workflows/mongodb.yml"
jobs:
  molecule:
    runs-on: ubuntu-20.04
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    strategy:
      fail-fast: true
      matrix:
        molecule_distro:
          - { "distro": "ubuntu-18.04", "command": "/lib/systemd/systemd" }
          - { "distro": "ubuntu-20.04", "command": "/lib/systemd/systemd" }
        collection_role:
          - mongodb
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: get list of files
        run: ls -lart

      - name: Install dependencies
        run: |
          sudo apt install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          python -m pip install --upgrade pip
          pip install ansible molecule molecule-containers molecule-docker ansible-lint

      - name: Get Ansible and Molecule Version
        run: |
          molecule --version
          ansible --version

      - name: Run role tests
        run: >-
          cd roles/${{ matrix.collection_role }} &&
          MOLECULE_CONTAINERS_BACKEND=docker
          MOLECULE_COMMAND=${{ matrix.molecule_distro.command }}
          MOLECULE_DISTRO=${{ matrix.molecule_distro.distro }}
          molecule --debug test
