---
name: ericsysmin.databases.mongodb
on:
  push:
    paths:
      - roles/mongodb/**
      - molecule/mongodb/**
      - .github/workflows/mongodb.yml
  pull_request:
    paths:
      - roles/mongodb/**
      - molecule/mongodb/**
      - .github/workflows/mongodb.yml
jobs:
  mongodb:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    strategy:
      fail-fast: true
      matrix:
        molecule_distro:
          - { distro: ubuntu-20.04, command: /lib/systemd/systemd }
          - { distro: ubuntu-22.04, command: /lib/systemd/systemd }
          # - { distro: debian-11, command: /lib/systemd/systemd }
        collection_role:
          - mongodb
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/ericsysmin/databases

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          sudo apt install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          python -m pip install --upgrade pip
          pip install ansible molecule yamllint ansible-lint molecule-plugins[docker]

      - name: Run role tests
        run: >-
          molecule --version &&
          ansible --version &&
          MOLECULE_COMMAND=${{ matrix.molecule_distro.command }}
          MOLECULE_DISTRO=${{ matrix.molecule_distro.distro }}
          molecule --debug test -s ${{ matrix.collection_role }}
